FROM debian:buster-slim

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

ARG RUST_BACKTRACE
ENV RUST_BACKTRACE=${RUST_BACKTRACE}

RUN apt-get update && apt-get install -y \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*
WORKDIR /app
COPY api /app/api
COPY .env /app/.env


EXPOSE 8080
CMD ["/app/api"]
